### ISSUE TITLE
version 0.9.10 Navbar and Slideme issue

### ISSUE THREAD

**Issue by garmax1** [giansi/gravstrap#1]
After updating to 0.9.10 slideme carousel shows in navbar. You can see in demo also http://gravstrap.diblas.net/home-page-with-carousel-header

**Comment by giansi** [comment]
Hi, thank you for reporting that problem. An accidentally wrong compiled css was added. Here's the fix https://github.com/giansi/gravstrap-theme/commit/6bfe79e9e7da289baa990a1d2db0a4a31437c2ee

**Comment by garmax1** [comment]
Ok. Thanks. I closed this issue because it's issue of gravstrap-theme not of plugin )
