### ISSUE TITLE
Blueprint

### ISSUE THREAD

**Issue by flaviocopes** [giansi/gravstrap#15]
Just stumbled on these small issues:
- Don't include `demo: none` or the link in admin is `http://localhost:8080/grav-admin/admin/plugins/none`
- Also, readme link gives a 404

**Comment by giansi** [comment]
Fixed, thank you. However, readme pretends that plugin's homepage is a github repo and that is not always true. Maybe a dedicated parameter could handle all cases.

**Comment by flaviocopes** [comment]
Yes, up to now it's a "de facto standard" but might be somewhere else.
