### ISSUE TITLE
attributes broken on link shortcode in v1.0.0-rc.2

### ISSUE THREAD

**Issue by AptusRoy** [giansi/gravstrap#2]
After upgrading to v1.0.0-rc.2 I noticed that extra attributes where not getting passed through to the html from the link shortcode.

This is because the shortcode is using variable "attributes":

```
'attributes' => $shortcode->getParameter('attributes'),
```

in gravstrap/shortcodes/Basic/LinkShortcode.php

but the template is expecting "link_attributes".

```
{% set attributes = parse_attributes(link_attributes) %}
```

in gravstrap/templates/basic/link.html.twig

thanks!

**Comment by giansi** [comment]
Thank for reporting! Fixed in new release.
