### ISSUE TITLE
Cannot change/edit Navbar/Menu Title anymore

### ISSUE THREAD

**Issue by axel-rank** [giansi/gravstrap#3]
In newest gravstrap release I can't change navbar/menu titles anymore.
If I open any md file in user/pages folder and change menu title nothing happens.
So where/how to change? Bug?

**Comment by giansi** [comment]
In order, to define the menu page link, Gravstrap looks for the "menu" property in each page header. When it is not defined, it falls back using the page "title" property.

**Comment by axel-rank** [comment]
Yes I know, and I changed title and menu property in page header and nothing happened/changed ?
Example: user/pages/02.home_single --> home_single_page.md
In page header I change title/menu property --> no result
Metadata changes work.
The same in all subfolders like _clients, _portfolio etc.
Changes of menu/title property in page header do not work.

In gravstrap 0.9.13 everythings working

**Comment by giansi** [comment]
Ok, the problem is with page cache. Navbar dynamically builds the menu so it cannot be cached. You must add the cache_enable: false property to pages/02.home_single/header/header.md and to pages/common/common.md to solve this issue. I will release a fix today.
