### ISSUE TITLE
google maps still not showing correctly

### ISSUE THREAD

**Issue by 4evermaat** [giansi/gravstrap#6]
I don't think issue #4 is fully fixed within gravstrap
I updated gravstrap to 1.0.3 and it still shows blue now for me instead of gray. 
![google maps not showing again 1 0 3](https://cloud.githubusercontent.com/assets/830306/13860167/9f95a768-ecb9-11e5-8a99-1d5021510aa3.gif)

I visited http://gravstrap.diblas.net/ . The map is better (shows marker, google logo, etc, but the full google map still does not load.  I visit https://www.google.com/maps/@41.897563,12.518114,11z?hl=en-US directly and the map shows just fine.  It is only within gravstrap theme that is the problem.

Are you guys using different coordinates?  
I'm using Google Chrome 49.0.2623.87 m (64 bit) and Firefox 38.x and windows 7 64 bit. I cleared browser cookies and cleared grav cache.  No luck
edit:  I tested http://gravstrap.diblas.net/  again from internet explorer 11.0.9600.18015 on my windows vps and I have the same problem.  But the [direct google maps link](https://www.google.com/maps/@41.90278,12.49637,12z?hl=en-US) displays fine

@giansi @Hanfrey can anyone upload a screenshot within their gravstrap website showing the google maps is fully displaying ok?

**Comment by Hanfrey** [comment]
Hello, here you can see my solution running.i did not test 1.0.3 yet. 
http://vps.hanfrey.de/grav/home

**Comment by 4evermaat** [comment]
I can confirm after updating the demo pages, google maps works ok.  but your [googlemaps shortcode](http://diblas.net/plugins/use-bootstrap-components-as-shortcodes-in-grav-cms/gravstrap-google-map-shortcode#upgrading) page example has not been updated.  The example is still showing a grey/blank google map.

**Comment by giansi** [comment]
Changing js_pipeline setting to false solves the issue, at the moment. I will investigate to to fix it when that setting is true
