### ISSUE TITLE
navbar manipulation submenu definition

### ISSUE THREAD

**Issue by 4evermaat** [giansi/gravstrap#7]
I tried to get more info on [navbar shortcode](http://diblas.net/plugins/use-bootstrap-components-as-shortcodes-in-grav-cms/gravstrap-navbar-shortcode).  The submenu function I am confused as to the different parameters.
`submenu="internal,components"`  what does 'internal' and 'components' mean?  Can I customize which menu items do NOT display in the submenu?

**Comment by tim-heinsohn** [comment]
@4evermaat I was a bit confused here, too. The solution: `submenu` contains a list of pages (page slugs without numeration) that are to display submenus. Once a page is in that list, the its menu entry will contain a submenu icon, no matter whether it has child pages or not. Visible child pages then “automatically” (via [`NavbarMenuShortcode::buildMenu()](https://github.com/giansi/gravstrap/blob/f47d1b2ff2017adf5efe74dba74dc831938a55a1/shortcodes/Bootstrap/NavbarMenuShortcode.php#L77-L106)`) will be added to that submenu.
