### ISSUE TITLE
copy to clipboard implementation

### ISSUE THREAD

**Issue by 4evermaat** [giansi/gravstrap#9]
I wanted to know if you could add the ability to [copy to clipboard](http://www.sitepoint.com/javascript-copy-to-clipboard/)?  You have text that is highlighted in the background and then there is a button to 'copy to clipboard'.   See the screenshot to see what I mean.

![getgrav copy to clipboard icon and function](https://cloud.githubusercontent.com/assets/830306/13981254/8d657dd8-f115-11e5-8f08-3596ff546662.gif)  
The people who wrote the [getgrav tutorials](learn.getgrav.org/) use it quite extensively.  But there is no documentation for the implementation.

I would like to just use a shortcode to implement this within any paragraph and call it a day.

**Comment by giansi** [comment]
I don't plan to add that shortcode in Gravstrap. It could be added to a specific plugin as explained here: https://github.com/getgrav/grav-plugin-shortcode-core#developing-shortcode-plugins
